import {
  FiActivity,
  FiAnchor,
  FiBookOpen,
  FiBox,
  FiClipboard,
  FiCoffee,
  FiFileText,
  FiHeart,
  FiPackage,
  FiTrendingUp,
  FiTruck,
  FiUsers,
} from 'react-icons/fi'
import type { SolutionSlug } from '../data/solutions'
import { buildWhatsAppHref } from '../lib/demo/mock'
import type { DemoAppConfig, DemoAppSlug } from '../lib/demo/types'

export const demoApps: DemoAppConfig[] = [
  {
    slug: 'hrms',
    solutionSlug: 'hrms',
    name: 'HRMS Demo',
    shortName: 'HRMS',
    category: 'Internal Operations',
    tagline: 'People operations, attendance, payroll, and hiring in one polished walkthrough.',
    summary: 'Show workforce visibility, approvals, payroll health, and hiring momentum with safe in-browser mock state.',
    accent: {
      primary: '#3659d9',
      secondary: '#7c8efc',
      surface: 'rgba(54, 89, 217, 0.1)',
      gradient: 'linear-gradient(135deg, #172554 0%, #22346a 46%, #3659d9 100%)',
      ink: '#0f172a',
      page: '#f5f8ff',
      panel: 'rgba(255,255,255,0.88)',
      line: 'rgba(148,163,184,0.22)',
    },
    icon: FiActivity,
    identity: {
      navStyle: 'enterprise-sidebar',
      densityMode: 'comfortable',
      cardStyle: 'soft',
      tableStyle: 'clean',
      previewVariant: 'hrms',
      typography: 'corporate',
      dashboardLabel: 'People command overview',
      motionStyle: 'calm',
      productHint: 'Corporate HR cockpit',
    },
    heroMetrics: [
      { label: 'Employees', value: '248', change: '+12 this quarter', tone: 'positive' },
      { label: 'Attendance', value: '96.4%', change: '+1.8% vs last month', tone: 'positive' },
      { label: 'Payroll Health', value: 'On track', change: 'Zero pending approvals', tone: 'neutral' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/HrmsDemoPage'),
  },
  {
    slug: 'hms',
    solutionSlug: 'healthcare-management',
    name: 'Hospital Management Demo',
    shortName: 'HMS',
    category: 'Healthcare',
    tagline: 'Front desk, appointments, billing, and ward operations with a client-ready hospital flow.',
    summary: 'Demonstrate patient movement, doctor schedules, collections, and occupancy without touching live records.',
    accent: {
      primary: '#0d9488',
      secondary: '#34d399',
      surface: 'rgba(13, 148, 136, 0.12)',
      gradient: 'linear-gradient(135deg, #083344 0%, #0f4f5f 46%, #0d9488 100%)',
      ink: '#082f49',
      page: '#f3fbfb',
      panel: 'rgba(255,255,255,0.92)',
      line: 'rgba(148,163,184,0.18)',
    },
    icon: FiHeart,
    identity: {
      navStyle: 'workflow-topbar',
      densityMode: 'compact',
      cardStyle: 'clinical',
      tableStyle: 'clinical',
      previewVariant: 'hms',
      typography: 'clinical',
      dashboardLabel: 'Clinical flow board',
      motionStyle: 'precise',
      productHint: 'Reception-to-billing flow',
    },
    heroMetrics: [
      { label: 'Today Appointments', value: '126', change: '14 walk-ins added', tone: 'neutral' },
      { label: 'Collections', value: 'Rs 4.8L', change: '+9% vs yesterday', tone: 'positive' },
      { label: 'Ward Occupancy', value: '82%', change: '12 beds available', tone: 'warning' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/HmsDemoPage'),
  },
  {
    slug: 'inventory',
    solutionSlug: 'inventory-management',
    name: 'Inventory Demo',
    shortName: 'Inventory',
    category: 'Distribution',
    tagline: 'Warehouse visibility, vendor coordination, and order control from one demo workspace.',
    summary: 'Demonstrate stock accuracy, purchase flow, vendor SLAs, and sample exports with static data and local state.',
    accent: {
      primary: '#ea580c',
      secondary: '#f59e0b',
      surface: 'rgba(234, 88, 12, 0.1)',
      gradient: 'linear-gradient(135deg, #111827 0%, #2b2f36 36%, #ea580c 100%)',
      ink: '#111827',
      page: '#f5f6f7',
      panel: 'rgba(255,255,255,0.95)',
      line: 'rgba(71,85,105,0.24)',
    },
    icon: FiBox,
    identity: {
      navStyle: 'operations-rail',
      densityMode: 'dense',
      cardStyle: 'industrial',
      tableStyle: 'warehouse',
      previewVariant: 'inventory',
      typography: 'operational',
      dashboardLabel: 'Warehouse control layer',
      motionStyle: 'mechanical',
      productHint: 'Stock and movement control',
    },
    heroMetrics: [
      { label: 'Active SKUs', value: '1,486', change: '98 flagged for reorder', tone: 'warning' },
      { label: 'Order Fill Rate', value: '97.1%', change: '+2.1% this week', tone: 'positive' },
      { label: 'Warehouse Value', value: 'Rs 2.7Cr', change: 'Across 4 storage zones', tone: 'neutral' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/InventoryDemoPage'),
  },
  {
    slug: 'parking',
    solutionSlug: 'parking-management',
    name: 'Truck Parking Demo',
    shortName: 'Parking',
    category: 'Operations',
    tagline: 'Live bay occupancy, entries, exits, and revenue flow in a premium operations shell.',
    summary: 'Show parking movement, bay allocation, occupancy, and billing with realistic local-only datasets.',
    accent: {
      primary: '#facc15',
      secondary: '#fb923c',
      surface: 'rgba(250, 204, 21, 0.14)',
      gradient: 'linear-gradient(135deg, #111111 0%, #232323 42%, #44403c 100%)',
      ink: '#fafaf9',
      page: '#121212',
      panel: 'rgba(23,23,23,0.88)',
      line: 'rgba(250,204,21,0.18)',
    },
    icon: FiTruck,
    identity: {
      navStyle: 'command-center',
      densityMode: 'live',
      cardStyle: 'tactical',
      tableStyle: 'board',
      previewVariant: 'parking',
      typography: 'command',
      dashboardLabel: 'Live yard board',
      motionStyle: 'urgent',
      productHint: 'Occupancy and movement board',
    },
    heroMetrics: [
      { label: 'Current Occupancy', value: '78%', change: '52 of 67 bays used', tone: 'warning' },
      { label: 'Daily Revenue', value: 'Rs 1.46L', change: '+11% vs avg day', tone: 'positive' },
      { label: 'Average Turnaround', value: '6h 12m', change: '2 fast-lane exits pending', tone: 'neutral' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/TruckParkingDemoPage'),
  },
  {
    slug: 'coaching',
    solutionSlug: 'coaching-management',
    name: 'Coaching Institute Demo',
    shortName: 'Coaching',
    category: 'Education',
    tagline: 'Admissions, attendance, timetables, and fees in a campus-style operating system.',
    summary: 'Walk clients through student batches, timetable planning, attendance capture, and fee follow-up with safe demo data.',
    accent: {
      primary: '#7c3aed',
      secondary: '#f472b6',
      surface: 'rgba(124,58,237,0.12)',
      gradient: 'linear-gradient(135deg, #2e1065 0%, #5b21b6 52%, #ec4899 100%)',
      ink: '#2e1065',
      page: '#faf5ff',
      panel: 'rgba(255,255,255,0.92)',
      line: 'rgba(167,139,250,0.24)',
    },
    icon: FiBookOpen,
    identity: {
      navStyle: 'campus-hub',
      densityMode: 'calendar',
      cardStyle: 'academic',
      tableStyle: 'roster',
      previewVariant: 'coaching',
      typography: 'campus',
      dashboardLabel: 'Institute operations hub',
      motionStyle: 'rhythmic',
      productHint: 'Timetable and batch hub',
    },
    heroMetrics: [
      { label: 'Students', value: '1,284', change: '92 new admissions this month', tone: 'positive' },
      { label: 'Attendance', value: '91.3%', change: 'Morning batches stronger', tone: 'neutral' },
      { label: 'Fee Collection', value: 'Rs 18.6L', change: '27 dues this week', tone: 'warning' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/CoachingDemoPage'),
  },
  {
    slug: 'ca',
    solutionSlug: 'accounting-firm',
    name: 'CA Firm Demo',
    shortName: 'CA Firm',
    category: 'Finance',
    tagline: 'Client work, compliance tracking, invoices, and recovery in a disciplined practice workspace.',
    summary: 'Show partners and firm managers a finance-first product with ledger visibility, filing checkpoints, and collection follow-up.',
    accent: {
      primary: '#0f766e',
      secondary: '#14b8a6',
      surface: 'rgba(15,118,110,0.12)',
      gradient: 'linear-gradient(135deg, #082f49 0%, #0f766e 56%, #14b8a6 100%)',
      ink: '#083344',
      page: '#f0fdfa',
      panel: 'rgba(255,255,255,0.94)',
      line: 'rgba(45,212,191,0.24)',
    },
    icon: FiFileText,
    identity: {
      navStyle: 'ledger-desk',
      densityMode: 'ledger',
      cardStyle: 'ledger',
      tableStyle: 'ledger',
      previewVariant: 'ca',
      typography: 'finance',
      dashboardLabel: 'Practice desk',
      motionStyle: 'methodical',
      productHint: 'Compliance and collections desk',
    },
    heroMetrics: [
      { label: 'Active Clients', value: '312', change: '41 filing cycles open', tone: 'neutral' },
      { label: 'Invoices Due', value: 'Rs 9.4L', change: '18 clients pending payment', tone: 'warning' },
      { label: 'GST On Track', value: '94%', change: 'Only 6 escalations', tone: 'positive' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/CaDemoPage'),
  },
  {
    slug: 'restaurant',
    solutionSlug: 'retail-takeaway',
    name: 'Restaurant Order Demo',
    shortName: 'Restaurant',
    category: 'Retail',
    tagline: 'Kitchen status, takeaway orders, and outlet revenue in a fast service board.',
    summary: 'Demonstrate live order movement, kitchen prep, counter flow, and item-level revenue without any live backend.',
    accent: {
      primary: '#dc2626',
      secondary: '#f59e0b',
      surface: 'rgba(220,38,38,0.12)',
      gradient: 'linear-gradient(135deg, #7f1d1d 0%, #b91c1c 42%, #f59e0b 100%)',
      ink: '#7f1d1d',
      page: '#fff7ed',
      panel: 'rgba(255,255,255,0.94)',
      line: 'rgba(251,146,60,0.24)',
    },
    icon: FiCoffee,
    identity: {
      navStyle: 'kitchen-board',
      densityMode: 'service',
      cardStyle: 'hospitality',
      tableStyle: 'kitchen',
      previewVariant: 'restaurant',
      typography: 'hospitality',
      dashboardLabel: 'Live service board',
      motionStyle: 'snappy',
      productHint: 'Kitchen and counter flow',
    },
    heroMetrics: [
      { label: 'Orders Today', value: '286', change: 'Peak at 8:15 PM', tone: 'positive' },
      { label: 'Kitchen SLA', value: '14 min', change: '3 orders delayed', tone: 'warning' },
      { label: 'Daily Sales', value: 'Rs 74,800', change: 'Combo sales up 12%', tone: 'positive' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/RestaurantDemoPage'),
  },
  {
    slug: 'shipping',
    solutionSlug: 'logistics-shipping',
    name: 'Shipping Demo',
    shortName: 'Shipping',
    category: 'Logistics',
    tagline: 'Shipment tracking, container status, milestones, and delivery coordination in one logistics workspace.',
    summary: 'Show clients a shipment-led product with manifests, timelines, alerts, and customer commitments held safely in the browser.',
    accent: {
      primary: '#2563eb',
      secondary: '#06b6d4',
      surface: 'rgba(37,99,235,0.12)',
      gradient: 'linear-gradient(135deg, #082f49 0%, #1d4ed8 52%, #06b6d4 100%)',
      ink: '#082f49',
      page: '#eff6ff',
      panel: 'rgba(255,255,255,0.94)',
      line: 'rgba(96,165,250,0.24)',
    },
    icon: FiPackage,
    identity: {
      navStyle: 'shipment-atlas',
      densityMode: 'tracking',
      cardStyle: 'tracking',
      tableStyle: 'manifest',
      previewVariant: 'shipping',
      typography: 'logistics',
      dashboardLabel: 'Shipment atlas',
      motionStyle: 'gliding',
      productHint: 'Milestones and container tracking',
    },
    heroMetrics: [
      { label: 'Active Shipments', value: '184', change: '31 priority consignments', tone: 'neutral' },
      { label: 'On-Time Delivery', value: '96.2%', change: '+1.4% this week', tone: 'positive' },
      { label: 'Exceptions', value: '7', change: '2 customs holds', tone: 'warning' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/ShippingDemoPage'),
  },
  {
    slug: 'port',
    solutionSlug: 'port-operations',
    name: 'Port Management Demo',
    shortName: 'Port',
    category: 'Port Operations',
    tagline: 'Vessel schedules, berth allocation, and cargo handling shown through a harbor operations surface.',
    summary: 'Present a marine-grade operations board with berths, cranes, cargo lots, and ETA risk without any backend dependency.',
    accent: {
      primary: '#0f766e',
      secondary: '#38bdf8',
      surface: 'rgba(14,116,144,0.12)',
      gradient: 'linear-gradient(135deg, #083344 0%, #0f766e 46%, #0284c7 100%)',
      ink: '#083344',
      page: '#ecfeff',
      panel: 'rgba(255,255,255,0.94)',
      line: 'rgba(34,211,238,0.24)',
    },
    icon: FiAnchor,
    identity: {
      navStyle: 'harbor-ops',
      densityMode: 'marine',
      cardStyle: 'marine',
      tableStyle: 'dock',
      previewVariant: 'port',
      typography: 'marine',
      dashboardLabel: 'Harbor operations board',
      motionStyle: 'tidal',
      productHint: 'Vessel and berth control',
    },
    heroMetrics: [
      { label: 'Vessels Today', value: '24', change: '4 high-priority berths', tone: 'warning' },
      { label: 'Cargo Throughput', value: '18.4k MT', change: '+8% vs weekly average', tone: 'positive' },
      { label: 'Berth Utilisation', value: '88%', change: '2 docks freeing by evening', tone: 'neutral' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/PortDemoPage'),
  },
  {
    slug: 'crm',
    solutionSlug: 'crm-sales',
    name: 'CRM Demo',
    shortName: 'CRM',
    category: 'Sales',
    tagline: 'Pipeline movement, lead scoring, next steps, and forecast visibility in a sales-first product.',
    summary: 'Show a board-led CRM experience with drag-style stage changes, deal notes, and rep accountability using local-only state.',
    accent: {
      primary: '#7c3aed',
      secondary: '#22c55e',
      surface: 'rgba(124,58,237,0.12)',
      gradient: 'linear-gradient(135deg, #1e1b4b 0%, #581c87 48%, #22c55e 100%)',
      ink: '#1e1b4b',
      page: '#faf5ff',
      panel: 'rgba(255,255,255,0.94)',
      line: 'rgba(167,139,250,0.24)',
    },
    icon: FiTrendingUp,
    identity: {
      navStyle: 'pipeline-studio',
      densityMode: 'pipeline',
      cardStyle: 'sales',
      tableStyle: 'pipeline',
      previewVariant: 'crm',
      typography: 'sales',
      dashboardLabel: 'Pipeline studio',
      motionStyle: 'energetic',
      productHint: 'Kanban-led sales product',
    },
    heroMetrics: [
      { label: 'Open Pipeline', value: 'Rs 3.8Cr', change: '27 active deals', tone: 'positive' },
      { label: 'Win Rate', value: '31%', change: '+4 pts this quarter', tone: 'positive' },
      { label: 'Stalled Deals', value: '5', change: 'Need follow-up today', tone: 'warning' },
    ],
    demoEnabled: true,
    requestDemoOnly: false,
    modulePath: () => import('../pages/demo/apps/CrmDemoPage'),
  },
]

export function getDemoAppBySlug(slug?: string) {
  return demoApps.find((app) => app.slug === slug)
}

export function getDemoAppBySolutionSlug(solutionSlug?: SolutionSlug) {
  return demoApps.find((app) => app.solutionSlug === solutionSlug)
}

export function getDemoRoute(slug: DemoAppSlug) {
  return `/demo/${slug}`
}

export function buildDemoRequestPath(appName?: string) {
  return appName ? `/request-demo?industry=${encodeURIComponent(appName)}&source=interactive-demo` : '/request-demo'
}

export function buildDemoWhatsAppHref(appName: string) {
  return buildWhatsAppHref(`Hi Qode27, I would like a tailored walkthrough for the ${appName} demo.`)
}
